// api/generate-site.js - Advanced Website Generator
import { randomBytes } from 'crypto';

const generatedSites = new Map();

function generateHTMLSite(description, requirements) {
  const siteId = randomBytes(8).toString('hex');
  const siteUrl = `https://${process.env.VERCEL_URL || 'localhost:3000'}/preview/${siteId}`;
  
  // Generate complete website based on description
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${escapeHtml(description.substring(0, 50))}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            color: #fff;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
        }
        
        header {
            text-align: center;
            padding: 4rem 0;
            animation: fadeInDown 1s ease;
        }
        
        h1 {
            font-size: 3rem;
            margin-bottom: 1rem;
            background: linear-gradient(135deg, #fff, #ffd89b);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }
        
        @keyframes fadeInDown {
            from {
                opacity: 0;
                transform: translateY(-30px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
        
        .features {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 2rem;
            margin: 4rem 0;
        }
        
        .feature-card {
            background: rgba(255, 255, 255, 0.1);
            backdrop-filter: blur(10px);
            padding: 2rem;
            border-radius: 1rem;
            transition: transform 0.3s ease, box-shadow 0.3s ease;
            animation: fadeInUp 0.8s ease;
        }
        
        .feature-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
        }
        
        @keyframes fadeInUp {
            from {
                opacity: 0;
                transform: translateY(30px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
        
        .btn {
            display: inline-block;
            padding: 1rem 2rem;
            background: linear-gradient(135deg, #667eea, #764ba2);
            color: white;
            text-decoration: none;
            border-radius: 0.5rem;
            transition: transform 0.3s ease, box-shadow 0.3s ease;
            animation: pulse 2s infinite;
        }
        
        .btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 5px 20px rgba(0, 0, 0, 0.3);
        }
        
        @keyframes pulse {
            0%, 100% {
                box-shadow: 0 0 0 0 rgba(102, 126, 234, 0.7);
            }
            50% {
                box-shadow: 0 0 0 10px rgba(102, 126, 234, 0);
            }
        }
        
        @media (max-width: 768px) {
            .container {
                padding: 1rem;
            }
            
            h1 {
                font-size: 2rem;
            }
            
            .features {
                grid-template-columns: 1fr;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>${escapeHtml(description.substring(0, 100))}</h1>
            <p>Generated by GLM-5 AI Agent</p>
        </header>
        
        <div class="features">
            <div class="feature-card">
                <h3>✨ AI-Powered</h3>
                <p>Built with cutting-edge GLM-5 technology</p>
            </div>
            <div class="feature-card">
                <h3>🚀 Fully Responsive</h3>
                <p>Works perfectly on all devices</p>
            </div>
            <div class="feature-card">
                <h3>💎 Modern Design</h3>
                <p>Sleek animations and gradients</p>
            </div>
        </div>
        
        <div style="text-align: center;">
            <a href="#" class="btn">Get Started</a>
        </div>
    </div>
    
    <script>
        console.log('Site generated by GLM-5 AI on ${new Date().toISOString()}');
        
        // Add smooth scroll
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener('click', function (e) {
                e.preventDefault();
                document.querySelector(this.getAttribute('href')).scrollIntoView({
                    behavior: 'smooth'
                });
            });
        });
    </script>
</body>
</html>`;
  
  generatedSites.set(siteId, {
    html,
    description,
    requirements,
    createdAt: Date.now(),
    url: siteUrl
  });
  
  return { siteId, url: siteUrl, html };
}

function escapeHtml(text) {
  const div = document?.createElement?.('div') || { textContent: '' };
  if (div.textContent !== undefined) {
    div.textContent = text;
    return div.innerHTML;
  }
  return text.replace(/[&<>]/g, function(m) {
    if (m === '&') return '&amp;';
    if (m === '<') return '&lt;';
    if (m === '>') return '&gt;';
    return m;
  });
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, GET, OPTIONS');
  
  if (req.method === 'OPTIONS') return res.status(200).end();
  
  if (req.method === 'GET') {
    const { id } = req.query;
    const site = generatedSites.get(id);
    if (!site) {
      return res.status(404).send('Site not found');
    }
    res.setHeader('Content-Type', 'text/html');
    return res.send(site.html);
  }
  
  if (req.method === 'POST') {
    const { description, requirements } = req.body;
    
    if (!description) {
      return res.status(400).json({ error: 'Description is required' });
    }
    
    try {
      const result = generateHTMLSite(description, requirements || '');
      res.status(200).json({
        success: true,
        siteId: result.siteId,
        url: result.url,
        message: 'Website generated successfully!'
      });
    } catch (error) {
      res.status(500).json({ error: 'Failed to generate website', details: error.message });
    }
  }
}
